version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hellloooo!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
